### PR TITLE
Upgrade Bazel version

### PR DESCRIPTION
**Pull request by Yannic**

### CODE REVIEW

**Review by TheGrizzlyDev — APPROVED** [review]

**Comment by TheGrizzlyDev** [comment]
@Yannic please sign the DCO

**Review by saraadams — COMMENTED** [review]
Why not 6.1.1?

**Comment by Yannic** [comment]
I wasn't aware there is a 6.1.1. Following up

**Comment by saraadams** [comment]
> I wasn't aware there is a 6.1.1. Following up

I only knew, because I was about to send out a PR to upgrade to 6.1.1 :)

**Pull request merged**
