### PR TITLE
Keep GitHub Actions up to date with GitHub's Dependabot

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/EngFlow/bazel_invocation_analyzer/blob/80c37d7eb69b3cc7b837a7f8330edb193e749362/.github/workflows/ci.yml#L12
Upgrade `v1` to `v4` -- https://github.com/actions/checkout/releases
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

### CODE REVIEW

**Comment by ulfjack** [comment]
We've decided to go with renovatebot for now, but thank you for your contribution.

**Comment by cclauss** [comment]
Yes, but it is not working...

**Comment by saraadams** [comment]
> Yes, but it is not working...

Can you clarify? What is not working?

**Comment by ulfjack** [comment]
We only enabled it after reviewing your PR today. Both the checkout action and one of the Bazel dependencies are now updated.

**Comment by cclauss** [comment]
Yeah... I guess it is still broken.

**Pull request closed without merging**
