### PR TITLE
Update external dependencies (jars from maven)

### PR DESCRIPTION
**Pull request by saraadams**

### CODE REVIEW

**Review by laszlocsomor — COMMENTED** [review]
What's up with the test failure?

**Comment by saraadams** [comment]
> What's up with the test failure?

I'm looking into it. It's related to updating byte-buddy.

**Comment by saraadams** [comment]
PTAL - I removed mockito and byte-buddy for now.

**Review by WillEngFlow — APPROVED** [review]

**Comment by WillEngFlow** [comment]
What could go wrong :shrug:

**Pull request merged**
